### PR TITLE
fix listItems option not allowing empty arrays

### PR DESCRIPTION
**Pull request by FelschR**
When setting the option `listItems: 0` arrays would still always be generated with at least one item in it.
This pull request fixes that behaviour.

### CODE REVIEW

**Comment by hamzahamidi** [comment]
Hi @FelschR Thank you for your PR. I just tested it & I still have the same issue with the following JSON schema:
```json

{
   "schema":{
      "type":"object",
      "properties":{
         "first_name":{
            "type":"string"
         },
         "last_name":{
            "type":"string"
         },
         "address":{
            "type":"object",
            "properties":{
               "street_1":{
                  "type":"string"
               },
               "street_2":{
                  "type":"string"
               },
               "city":{
                  "type":"string"
               },
               "state":{
                  "type":"string",
                  "enum":[
                     "AL",
                     "AK",
                     "AS",
                     "AZ",
                     "AR",
                     "CA",
                     "CO",
                     "CT",
                     "DE",
                     "DC",
                     "FM",
                     "FL",
                     "GA",
                     "GU",
                     "HI",
                     "ID",
                     "IL",
                     "IN",
                     "IA",
                     "KS",
                     "KY",
                     "LA",
                     "ME",
                     "MH",
                     "MD",
                     "MA",
                     "MI",
                     "MN",
                     "MS",
                     "MO",
                     "MT",
                     "NE",
                     "NV",
                     "NH",
                     "NJ",
                     "NM",
                     "NY",
                     "NC",
                     "ND",
                     "MP",
                     "OH",
                     "OK",
                     "OR",
                     "PW",
                     "PA",
                     "PR",
                     "RI",
                     "SC",
                     "SD",
                     "TN",
                     "TX",
                     "UT",
                     "VT",
                     "VI",
                     "VA",
                     "WA",
                     "WV",
                     "WI",
                     "WY"
                  ]
               },
               "zip_code":{
                  "type":"string"
               }
            }
         },
         "birthday":{
            "type":"string"
         },
         "notes":{
            "type":"string"
         },
         "phone_numbers":{
            "type":"array",
            "items":{
               "type":"object",
               "properties":{
                  "type":{
                     "type":"string",
                     "enum":[
                        "cell",
                        "home",
                        "work"
                     ]
                  },
                  "number":{
                     "type":"string"
                  }
               },
               "required":[
                  "type",
                  "number"
               ]
            }
         }
      },
      "required":[
         "last_name"
      ]
   },
   "layout":[
      {
         "type":"flex",
         "flex-flow":"row wrap",
         "items":[
            "first_name",
            "last_name"
         ]
      },
      {
         "key":"address.street_1",
         "title":"Address",
         "placeholder":"Street"
      },
      {
         "key":"address.street_2",
         "notitle":true
      },
      {
         "type":"div",
         "display":"flex",
         "flex-direction":"row",
         "items":[
            {
               "key":"address.city",
               "flex":"3 3 150px",
               "notitle":true,
               "placeholder":"City"
            },
            {
               "key":"address.state",
               "flex":"1 1 50px",
               "notitle":true,
               "placeholder":"State"
            },
            {
               "key":"address.zip_code",
               "flex":"2 2 100px",
               "notitle":true,
               "placeholder":"Zip Code"
            }
         ]
      },
      {
         "key":"birthday",
         "type":"date"
      },
      {
         "key":"phone_numbers",
         "type":"array",
         "listItems":0,
         "items":[
            {
               "type":"div",
               "displayFlex":true,
               "flex-direction":"row",
               "items":[
                  {
                     "key":"phone_numbers[].type",
                     "flex":"1 1 50px",
                     "notitle":true,
                     "placeholder":"Type"
                  },
                  {
                     "key":"phone_numbers[].number",
                     "flex":"4 4 200px",
                     "notitle":true,
                     "placeholder":"Phone Number"
                  }
               ]
            }
         ]
      },
      {
         "type":"section",
         "title":"Notes",
         "expandable":true,
         "expanded":false,
         "items":[
            {
               "key":"notes", 
               "type":"textarea",
               "notitle":true
            }
         ]
      }
   ],
   "data":{
      "first_name":"Jane",
      "last_name":"Doe",
      "address":{
         "street_1":"123 Main St.",
         "city":"Las Vegas",
         "state":"NV",
         "zip_code":"89123"
      },
      "birthday":"1999-09-09",
      "notes":"(This is an example of an uninteresting note.)"
   }
}

**Comment by FelschR** [comment]
Apparently this seems to happen when flex layout is used.
When I change the `phone_numbers` array's layout definition to the following it works:
```js
{
    key: "phone_numbers",
    type: "array",
    listItems: 0,
    items: [
        {
            key: "phone_numbers[].type",
            placeholder: "Type"
        },
        {
            key: "phone_numbers[].number",
            placeholder: "Phone Number"
        }
    ]
},
```

While investigating this I've come across another issue:
When `data` is already supplied `default` values of array items don't work (neither for the first item nor when adding additional items). It only works when `data` is initially undefined.
`default` values on the root level seem unaffected by this.

**Comment by FelschR** [comment]
Perhaps we could merge this pull request and create a new issue for investigating why this doesn't work with flex layout? As long as the change doesn't break any existing behaviour it would still be an improvement.

I was able to fix the array item w/ `default` problem by setting the `setSchemaDefaults` form option to `true` instead of `"auto"`.

**Comment by paragraval** [comment]
@hamzahamidi Any plans of merging this PR ?
I tried the layout for array (without flex) as mentioned in https://github.com/hamzahamidi/Angular6-json-schema-form/pull/68#issuecomment-459713729 and it worked for me.

**Comment by FelschR** [comment]
@hamzahamidi It's been a while but I got around to identify the issue with the flex layout and I was able to fix it.

**Comment by mkormendy** [comment]
@hamzahamidi did this get pulled in?

**Pull request closed without merging**
