### PR TITLE
feat(locales): add Brazilian Portuguese

### PR DESCRIPTION
**Pull request by guileh**

### CODE REVIEW

**Comment by hamzahamidi** [comment]
LGTM but can you rename the file to `pt-br-validation-messages.ts`
Also the commit should be `feat(locales): add Brazilian Portuguese`

**Comment by hamzahamidi** [comment]
You dont need to close the pr just add a new commit with the fix or rewrite the comit and push force @guileh

**Comment by guileh** [comment]
Oh! Now it's late... I did it ...     : ^0

**Comment by guileh** [comment]
Sorry for that.

**Pull request closed without merging**
