### PR TITLE
Extract frameworks as separate packages

### PR DESCRIPTION
**Pull request by alekart**
Unbundle the form builder frameworks (bs3, bs4, material) from the form builder module and add it as separate project libraries that should be installed as dependencies into a project along the base `angular6-json-schema-form` module.
(This implies that the frameworks should be published on npm as separate packages)

This will limit the dependencies and avoid installing unwanted angular packages as `Material` in a project that does not use Material Design and install a framework we actually need. 

This should also allow developers to make their own frameworks without cloning the entire `angular6-json-schema-form` repository and just publish their framework as an npm package.

The NoFramework (plain HTML) is still bundled with the form so we can use out of the box.

### CODE REVIEW

**Comment by hamzahamidi** [comment]
Great idea! I'll check this asap

**Comment by hamzahamidi** [comment]
I was thinking since you suggested using ajsf as a prefix. We'll publish the repository like this:
@ajsf/material
@ajsf/core maybe for the plain HTML version 
@ajsf/bootstrap3
@ajsf/bootstrap4

**Comment by hamzahamidi** [comment]
Merged in #170

**Comment by alekart** [comment]
👍 Glad it was integrated! Thx

**Pull request closed without merging**
